#pragma once
#define ADD 1
#define REVISE 2
#define REMOVE 3
#define SEARCH 5
#define LIST 6
#define UPDATE 7
#define NAMEDT 8
#define PNUMEDT1 9
#define PNUMEDT2 10
#define PNUMEDT3 11
#define MAILEDT 12
#define MAILDOMAIN 13
#define HOMEADDR 14
#define ETCEDT 15
#define SAVEBTN 16
#define CNCLBTN 17
#define SEE 18
#define OK 19
#define RSVEBTN 20
#define LOGINBTN 21
#define MKUSRBTN 22
#define ADDUSERBTN 23
#define RMSETCHK 24
#define USERSETBTN 25
#define APPLYBTN 26
#define SETCNCLBTN 27
#define TRSCNLIST 28
#define TRSCNDELBTN 29